[package]
name = "async_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.19.0"
eframe = { version = "0.19.0", features = ["persistence"] }
serde = { version = "1", features = ["derive"] }
bounded-vec-deque = "0.1.1"
tracing-subscriber = "0.3"
egui_dock = "0.2.1"
tracing = "0.1.37"
anyhow = "1.0.66"
# tokio = { version = "1.3.0", features = ["full"] }
smol = "1.3.0"
poll-promise = { git = "https://github.com/EmbarkStudios/poll-promise", features = ["smol", "smol_tick_poll"] }
once_cell = "1.3.0"
